### ISSUE TITLE
Unclear what to use for USER and REPO

### ISSUE THREAD

**Issue by ojw28** [presidentbeef/github-auto-locker#7]
Firstly, thanks for the great tool! I found it a bit unclear what values to use for USER and REPO though. For https://github.com/google/ExoPlayer I was trying things like:

github-auto-locker ojw28 ExoPlayer token
github-auto-locker ojw28 google/ExoPlayer token

But actually I should have been doing:

github-auto-locker google ExoPlayer token

I think the README could benefit from a few examples or some clarification for cases like mine, where the repository is owned by an organization rather than by me. Alternatively, it would be awesome if you could just give the URL to the tool and have it do the rest, like:

github-auto-locker https://github.com/google/ExoPlayer token

**Comment by presidentbeef** [comment]
Thanks for the feedback, @ojw28! I definitely did not consider organization repositories. Feel free to open a PR for updating the README :)
